### ISSUE TITLE
Remove script id prefix (?)

### ISSUE THREAD

**Issue by a-guerrero** [radixzz/html-shader-plugin#1]
Currently the type of shader is set as a prefix of the script id attribute, perhaps it is a good idea to leave this prefix as a `data-type` attribute, maybe it is kind of redundant since the type attribute is defined as `x-fragment` and `x-vertex`?. I think it would be better to remove it from the id, I'm suggesting this because I override the id, as documented, expecting that value would be the exact id.

``` html
<script type="x-shader/x-fragment" data-type="fragment" id="custom-shader-name">
    fragment files content...
</script>
```

✌️

**Comment by vanrez-nez** [comment]
Done. Please update your package version to `1.0.4`
I'll leave the tags without the `data-type` attribute as you suggested, thx for the feedback.  :punch:
